# Use a base image with Java
FROM gradle:jdk21 as builder

# Set the working directory
WORKDIR /app

# Copy the project into the Docker image
COPY . /app

# Build the Spring Boot application
RUN gradle build

# Start a new stage to create a smaller image
FROM openjdk:21

# Set the working directory
WORKDIR /app

# Copy the built .jar file from the builder stage
COPY --from=builder /app/build/libs/*.jar /app

# Expose the port the application runs on
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "/app/react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.jar"]